### ISSUE TITLE
Add Dark mode

### ISSUE THREAD

**Issue by Yatharth-2003** [iamneeraj542/Assignment-Website#11]
I would like to add Dark-Mode in your website. 
Please assign me this under Hacktober fest.

**Comment by neeraj542** [comment]
sorry, this is command is out of plan. Please figure anything else

**Comment by iamneeraj542** [comment]
> I would like to add Dark Mode to your website. Please assign me this under Hacktober fest.

yes, should go with this issue and create a new file named grey-dark in this repo. For a better understanding, you can visit GeekForGeeks to check how they created this feature and add it.

**Comment by neeraj542** [comment]
I want to work on this issue please assign me also

**Comment by iamneeraj542** [comment]
okay with this issue

**Comment by neeraj542** [comment]
thanks

**Comment by iamneeraj542** [comment]
close #16 #17
